import { Inter } from "next/font/google";
import type { Metadata } from "next";
import HeaderNavAdmin from "@/components/example/navbaruser";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ERP DASHBOARD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`${inter.className} w-full min-h-screen`}>
   
      <div className="flex h-full">
      

    
        <div className="flex-1 flex flex-col">
          <HeaderNavAdmin />
          <main className="flex-grow">{children}</main>
        </div>
      </div>
    </div>
  );
}
