import { Inter } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ERP DASHBOARD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} >
        {/* Flex container for sidebar and main content */}
        <div className="flex min-h-screen">
          {/* Sidebar */}
          {/* <SidebarDemo /> */}

          {/* Main content */}
          {/* <main className="flex-1"> */}
            {/* <HeaderNavAdmin /> Optional Header/Nav component */}
            {children}
          {/* </main> */}
        </div>
      </body>
    </html>
  );
}
